import tkinter as tk
from tkinter import *

window = tk.Tk()
window.title('POKEMON ADVENTURE')
window.geometry('700x700')

map = tk.PhotoImage(file='main.png')
minimap = tk.PhotoImage(file='minimap.png')
compass = tk.PhotoImage(file='compass.png')
logo = tk.PhotoImage(file='logo.png')

titlelbl = tk.Label(window, text='POKEMON ADVENTURE')
maplbl = tk.Label(window, image=map)
compasslbl = tk.Label(window, image=compass)
nwbutt = tk.Button(window, text='NW', width='3', height='1')
nbutt = tk.Button(window, text='N', width='3', height='1')
nebutt = tk.Button(window, text='NE', width='3', height='1')
ebutt = tk.Button(window, text='E', width='3', height='1')
sebutt = tk.Button(window, text='SE', width='3', height='1')
sbutt = tk.Button(window, text='S', width='3', height='1')
swbutt = tk.Button(window, text='SW', width='3', height='1')
wbutt = tk.Button(window, text='W', width='3', height='1')
logolbl = tk.Label(window, image=logo)
minilbl = tk.Label(window, text='MINI MAP')
minimaplbl = tk.Label(window, image=minimap)
mapbutt = tk.Button(window, text='MAP', width='13', height='2')
invbutt = tk.Button(window, text='INVENTORY', width='13', height='2')
pokebutt = tk.Button(window, text='POKEDEX', width='13', height='2')
rostbutt = tk.Button(window, text='ROSTER', width='13', height='2')
jourbutt = tk.Button(window, text='JOURNAL', width='13', height='2')
helpbutt = tk.Button(window, text='HELP', width='13', height='2')
shopbutt = tk.Button(window, text='SHOP', width='13', height='2')

titlelbl.place(x=250,y=10)
maplbl.place(x=10,y=40)
#compasslbl.place(x=10,y=490)
nwbutt.place(x=10,y=490)
nbutt.place(x=41,y=490)
nebutt.place(x=72,y=490)
ebutt.place(x=72,y=516)
sebutt.place(x=72, y=542)
sbutt.place(x=41,y=542)
swbutt.place(x=10,y=542)
wbutt.place(x=10, y=516)
logolbl.place(x=275,y=510)
minilbl.place(x=540,y=65)
minimaplbl.place(x=520,y=90)
mapbutt.place(x=520,y=190)
invbutt.place(x=520,y=231)
pokebutt.place(x=520,y=272)
rostbutt.place(x=520,y=313)
jourbutt.place(x=520,y=354)
helpbutt.place(x=520,y=395)
shopbutt.place(x=520,y=436)

window.mainloop()

#done